title: Wiki
description: Project documentation

url: https://lengthenedgradient.github.io
baseurl: /Wiki

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

search_enabled: true