title: Wiki
description: Project documentation

url: https://lengthenedgradient.github.io
baseurl: /Wiki

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

search_enabled: true
nav_expand: true

# Callout configuration
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
