title: ACF-3 Wiki
description: Official ACF-3 Wiki by the ACF Team

url: https://ACF-Team.GitHub.io
baseurl: /Wiki

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme
  - jekyll-last-modified-at

search_enabled: true
nav_expand: true
favicon_ico: /assets/images/favicon.ico

last-modified-at:
  date-format: '%d-%b-%y'

# Callout configuration
callouts:
  highlight:
    title: Important
    color: yellow
  notice:
    title: Notice
    color: green
  warning:
    title: Warning
    color: red

color_scheme: dark

back_to_top: true
back_to_top_text: "Back to top"

aux_links:
  ACF-3 Gmod Server:
    - steam://connect/76.146.209.119:27017
  ACF-3 Discord:
    - https://discord.gg/jf4cwarPUG
  ACF-3 On Workshop:
    - https://steamcommunity.com/sharedfiles/filedetails/?id=3248769144
  ACF-3 On GitHub:
    - https://GitHub.com/ACF-Team/ACF-3